server/config/routes.rb
Rails.application.routes.draw do
  #
  # For Clearance gem
  #
  resources :passwords, controller: "clearance/passwords", only: %i[create new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
             controller: "clearance/passwords",
             only: %i[create edit update]
  end

  get "/sign_in" => "clearance/sessions#new", :as => "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", :as => "sign_out"
  # get "/sign_up" => "clearance/users#new", as: "sign_up"

  ActiveAdmin.routes(self)

  #
  # Lexicon routes
  #
  root "welcome#index"
  get "/demo", to: "welcome#demo"
  get "/demo_multiple_providers", to: "welcome#demo_multiple_providers"
  get "/edit", to: "welcome#edit"
  get "/testing", to: "welcome#testing"

  get "/contact", to: "welcome#contact"
  get "/features", to: "welcome#features"
  get "/pricing", to: "welcome#pricing"

  # API routes
  put "/update", to: "api#update"
  put "/cookie_auth_update", to: "api#cookie_auth_update"
end

server/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

server/app/models/client_app.rb
# A Nitid app that uses this LexiconServer to save content edits.
class ClientApp < ApplicationRecord
  has_and_belongs_to_many :users

  def self.ransackable_associations(_auth_object = nil)
    ["users"]
  end

  def self.ransackable_attributes(_auth_object = nil)
    %w[
      adapter
      app_url
      created_at
      git_branch
      github_api_token
      github_repo
      github_user
      id
      name
      slack_workflow_url
      updated_at
    ]
  end

  # ActiveAdmin uses this for display
  def title
    "#{name} (#{app_url})"
  end

  def lexicon_adapter
    config_hash = {
      class: adapter,
      access_token: github_api_token,
      repo: github_repo,
      branch: git_branch,
    }
    LexServer::Adapter.configure(config_hash)
  end
end

server/app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  has_and_belongs_to_many :client_apps

  def self.ransackable_attributes(_auth_object = nil)
    %w[
      confirmation_token
      created_at
      email
      encrypted_password
      id
      is_admin
      remember_token
      updated_at
    ]
  end

  def self.ransackable_associations(_auth_object = nil)
    ["client_apps"]
  end

  # Allows admin > users to edit user, without changing password
  def skip_password_validation?
    true
  end
end

server/app/controllers/api_controller.rb
require "argon2"
require "jwt"
require "httparty"

def permitted_changes(params)
  params.require(:changes).map { |c| c.permit(:filename, :key, :newValue) }
end

class ApiController < ApplicationController
  JWT_ALGORITHM = "HS256".freeze

  before_action :authenticate_jwt_header, except: [:cookie_auth_update]
  skip_before_action :verify_authenticity_token, except: [:cookie_auth_update] # check CSRF
  before_action :require_login, only: [:cookie_auth_update]

  # Update API endpoint, authenticated via JWT token in header
  def update
    # CORS headers
    response.headers[
      "Access-Control-Allow-Origin"
    ] = ApiController.cors_friendly_origin(@authenticated_client_app.app_url)

    changes = permitted_changes(params)

    if @authenticated_client_app.slack_workflow_url.present?
      ApiController.slack_alert(
        @authenticated_client_app,
        @authenticated_user.email,
        changes,
      )
    end

    begin
      # SECURITY NOTE: Someone can send any filename, and we will try to modify it. We are trusing
      # our authenticated users.
      lexicon_saver.update_changes(@authenticated_user.email, changes)
      response = { successful: true, error: nil }
    rescue StandardError => e
      response = { successful: false, error: e.inspect }
    end

    render json: response
  end

  def self.cors_friendly_origin(origin_url)
    uri = URI(origin_url)

    return "#{uri.scheme}://#{uri.host}" if uri.port == 80 || uri.port == 443

    "#{uri.scheme}://#{uri.host}:#{uri.port}"
  end

  # Return the token that 'authenticate_jwt_header' requires
  def self.lexicon_server_token(user, client_app)
    jwt_expiration_time =
      ENV
        .fetch("JWT_TEST_DURATION_MINUTES", (12 * 60))
        .to_i
        .minutes
        .from_now
        .to_i
    payload = {
      userId: user.id,
      clientAppId: client_app.id,
      exp: jwt_expiration_time,
    }
    JWT.encode(payload, JWT_SECRET, JWT_ALGORITHM)
  end

  def self.slack_alert(client_app, whodunnit, changes)
    message =
      "User \"#{whodunnit}\" on app #{client_app.app_url} has changed Lexicon text: \n"
    changes.each do |change|
      message += "\"#{change["key"]}\" has changed to \"#{change["newValue"]}\""
      message += "\n"
    end
    response =
      HTTParty.post(
        client_app.slack_workflow_url,
        body: { "message" => message }.to_json,
        headers: {
          "Content-Type" => "application/json",
        },
      )

    case response.code
    when 200
      "slack_alert for #{client_app.app_url}: lexicon message sent to slack"
    when 404
      "slack_alert for #{client_app.app_url}: slack not found"
    else
      "slack_alert for #{client_app.app_url}: error #{response.code}"
    end
  end

  private

  def lexicon_saver
    LexServer::Saver.new(@authenticated_client_app.lexicon_adapter)
  end

  # Examine the 'Authorization: Bearer <JWT token>' header, check signature
  # sets '@authenticated_user' and '@authenticated_client_app'
  def authenticate_jwt_header
    @authenticated_user = nil
    @authenticated_client_app = nil
    pattern = /^Bearer /
    header = request.headers["Authorization"]

    unless header&.match(pattern)
      return(
        render_error(
          "Lexicon Server: Missing token from client app via HTTP authorization header.",
          :forbidden,
        )
      )
    end

    token = header.gsub(pattern, "")
    begin
      payload = JWT.decode(token, JWT_SECRET, true, algorithm: JWT_ALGORITHM)[0]
      @authenticated_user = User.find(payload["userId"])
      @authenticated_client_app = ClientApp.find(payload["clientAppId"])
    rescue JWT::VerificationError,
           JWT::DecodeError,
           ActiveRecord::RecordNotFound => e
      render_error(
        "Lexicon Server: Invalid token from client app: #{e}",
        :forbidden,
      )
    end
  end

  # Standard format for API responses
  def api_response(successful:, error: nil)
    { successful:, error: }
  end

  def render_error(message, status)
    render json: api_response(successful: false, error: message), status:
  end
end

server/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  protect_from_forgery with: :exception
end

server/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :require_login, except: [:index]

  def index
  end

  def edit
    @message_of_day = ENV.fetch("MESSAGE_OF_DAY", nil)
    @client_app_links =
      current_user
        .client_apps
        .order(:github_repo, :name)
        .map do |client_app|
          lexicon_server_token =
            ApiController.lexicon_server_token(current_user, client_app)
          url_with_token =
            "#{client_app.app_url}?lexiconServerToken=#{lexicon_server_token}"

          {
            url: url_with_token,
            name: client_app.name,
            git_branch: client_app.git_branch,
            github_repo: client_app.github_repo,
          }
        end
  end

  def demo
  end

  def testing
  end

  def demo_multiple_providers
  end
end

server/app/views/application/_masthead.html.erb
<div id="masthead_partial">

  <nav class="masthead">
    <h1> Lexicon Server </h1>

    <a href="/edit"> Apps to Edit </a>
    &nbsp; • &nbsp;
    <% if current_user.is_admin %>
      <a href="/admin/client_apps"> Admin </a>
      &nbsp; • &nbsp;
    <% end %>
    Welcome <%= current_user.email %>
    &nbsp; • &nbsp;
    <%= button_to 'Sign out', sign_out_path, method: :delete %>
  </nav>

  <% if notice.present? %>
    <div class="flash_notice"> <%= notice %></div>
  <% end %>
  <% if alert.present? %>
    <div class="flash_alert"> <%= alert %></div>
  <% end %>
</div>

server/app/views/layouts/application.html.erb
<%
  body_classes = [
    "#{params[:controller]}_controller",
    "#{params[:action]}_action"
  ].join(" ")
%>
<!DOCTYPE html>
<html>
  <head>
    <title>LexiconServer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="<%= body_classes %>">
    <%= yield %>
  </body>
</html>

server/app/views/welcome/_demo_nav.html.erb
<nav class="demo_nav" style="padding: 20px 0;" >
  <%= link_to "Demo", demo_path  %>
  |
  <%= link_to "Multiple Providers Demo", demo_multiple_providers_path %>
</nav>

server/app/views/welcome/_footer.html.erb
<footer style=" margin: 40px -8px -8px -8px; justify-content: space-between;
">
  <div class="menu" style="display: flex; justify-content: space-between; align-items: center; padding: 15px; background-color: #6A5ACD;">
    <h1 style="font-size: 24px; color: #87CEEB; margin: 0; letter-spacing: 6px; text-shadow: 1px 1px 2px #D3D3D3;">
      LEXICON
    </h1>
    <p style="color: #e0e0e0; margin: 0;">&copy; 2024 Nitidbit. All rights reserved.</p>
  </div>
</footer>

server/app/views/welcome/_menu.html.erb
<style>
  .menu {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 15px;
    background-color: #6A5ACD;
    margin: -8px -8px 0 -8px
  }

  .menu h1 {
    font-size: 24px;
    color: #87CEEB;
    margin: 0;
    letter-spacing: 6px;
    text-shadow: 1px 1px 2px rgba(211, 211, 211, 0.7);
  }

  .menu a {
    text-decoration: none;
    color: #e0e0e0;
    font-size: 16px;
  }
</style>
<div class="menu">
  <h1>
    LEXICON
  </h1>
  <div style="display: flex; gap: 20px;">
    <%= link_to "Home", "/" %>
    <%= link_to "Features", "features" %>
    <%= link_to "Demo", demo_path  %>
    <%= link_to "Pricing", "pricing" %>
    <%= link_to "Contact", "contact" %>
  </div>
</div>

server/app/views/welcome/contact.html.erb
<%= render 'menu' %>

<div style="max-width: 1200px; padding: 40px; display: flex; flex-wrap: wrap; gap: 40px;">
  <div style="flex: 1; min-width: 300px;">
    <h2 style="font-size: 28px; margin-bottom: 20px;">Contact Us</h2>
    <form action="/contact" method="post" style="display: flex; flex-direction: column;">
      <label for="name" style="margin-bottom: 5px;">
        Name
      </label>
      <input type="text" id="name" name="name" required style="padding: 10px; margin-bottom: 20px; border: 1px solid #ccc; border-radius: 5px;"/>

      <label for="email" style="margin-bottom: 5px;">
        Email
      </label>
      <input type="email" id="email" name="email" required style="padding: 10px; margin-bottom: 20px; border: 1px solid #ccc; border-radius: 5px;"/>

      <label for="message" style="margin-bottom: 5px;">
        Message
      </label>
      <textarea id="message" name="message" rows="5" required style="padding: 10px; margin-bottom: 20px; border: 1px solid #ccc; border-radius: 5px;"></textarea>

      <button type="submit" style="padding: 10px; background-color: #6A5ACD; color: white; border: none; border-radius: 5px; cursor: pointer;">Send Message</button>
    </form>
  </div>

  <div style="flex: 1; min-width: 300px">
    <h2 style="font-size: 28px; margin-bottom: 20px;">Get in Touch</h2>
    <p style="margin-bottom: 10px;">
      <a href="mailto:info@nitidbit.com" style="text-decoration: none; color: #6A5ACD;">info@nitidbit.com</a>
    </p>
    <p style="margin-bottom: 10px;">
      <a href="tel:+141532NITID" style="text-decoration: none; color: #6A5ACD;">+1 415 32 NITID</a>
    </p>
    <p style="margin-bottom: 10px;">149 New Montgomery St, Suite 506<br>San Francisco, CA 94105<br>USA</p>

    <h3 style="margin-top: 40px;">Follow Us</h3>
    <div style="display: flex; gap: 10px;">
      <a href="https://www.linkedin.com/company/nitid-bit-llc/" style="text-decoration: none; color: #6A5ACD;">LinkedIn</a>
    </div>
  </div>
</div>

<%= render 'footer' %>

server/app/views/welcome/demo.html.erb
<%= render 'masthead' %>
<%= render 'menu' %>

<%= javascript_include_tag('DemoComponent') %>
<%= stylesheet_link_tag('DemoComponent') %>

<h1> React Demo page </h1>

<div class="placeholder-DemoComponent"></div>

<%= render 'footer' %>

server/app/views/welcome/demo_multiple_providers.html.erb
<%= render 'masthead' %>
<%= render 'menu' %>


<%= javascript_include_tag('DemoMultipleProviders') %>
<%#= stylesheet_link_tag('DemoMultipleProviders') %>

<h1> Demo Multiple Providers </h1>

<div class="placeholder-DemoMultipleProviders"></div>

server/app/views/welcome/edit.html.erb
<%= render 'masthead' %>

<% if @message_of_day.present?  %>
  <p class='message-of-the-day'>
  <strong> Message of the Day </strong> —
    <%= @message_of_day %>
  </p>
<% end %>

<main>

  <h2>Apps to Edit</h2>
  <p>
    Click on one of these links to enable Lexicon editing on that app. When you click on a link below,
    you will see Edit Lexicon buttons around parts of your app. These buttons open the editor and
    allow you to change text. Editing is enabled as long as your browser is open. If you want to edit
    later, you will have to sign-in at this Lexicon Server again.
  </p>

  <table class='app_links'>
    <tr>
      <th> App Name </th>
      <th> Github Repo </th>
      <th> Git Branch </th>
    </th>
    <% @client_app_links.each do |link| %>
      <tr>
        <td>
          <a href="<%= link[:url] %>">
            <%= link[:name] %>
          </a>
        </td>
        <td>
          <%= link[:github_repo] %>
        </td>
        <td>
          <%= link[:git_branch] %>
        </td>
      </tr>
    <% end %>
  </table>
</main>

server/app/views/welcome/features.html.erb
<%= render 'menu' %>

<div style="padding: 20px;">
  <p>Exciting things are coming...</p>
</div>

<%= render 'footer' %>

server/app/views/welcome/index.html.erb
<h1>Lexicon</h1>
<p>
  Something exciting is brewing...
</p>

server/app/views/welcome/pricing.html.erb
<%= render 'menu' %>

<div style="padding: 40px;">
  <h1 style="font-size: 36px; text-align: center; margin-bottom: 40px;">Pricing Plans</h1>

  <div style="display: flex; justify-content: space-between; flex-wrap: wrap; gap: 20px;">
    <!-- Plan 1: Basic -->
    <div style="flex: 1; min-width: 280px; border-radius: 10px; padding: 20px; text-align: center; background: linear-gradient(to bottom, rgba(30, 144, 255, 0.2), rgba(106, 90, 205, 0.2)); border: 2px solid #6A5ACD;">
      <h2 style="font-size: 28px; color: #6A5ACD;">Basic</h2>
      <p style="font-size: 32px; color: #6A5ACD;">FREE</p>
      <ul style="font-size: 18px; list-style-type: none; padding: 0; margin: 20px 0;">
        <li>1 User</li>
        <li>Basic Features</li>
        <li>Email Support</li>
        <li>Up to 3 git commits/hour<li>
      </ul>
      <p style="font-size: 22px; color: #6A5ACD;">For the hobbyist</h4>
      <%# button style="padding: 10px 20px; background-color: #6A5ACD; color: white; border: none; border-radius: 5px; cursor: pointer;">Get Started</button %>
    </div>

    <!-- Plan 2: Standard -->
    <div style="flex: 1; min-width: 280px; border-radius: 10px; padding: 20px; text-align: center; background: linear-gradient(to bottom, rgba(30, 144, 255, 0.2), rgba(106, 90, 205, 0.2)); border: 2px solid #6A5ACD;">
      <h2 style="font-size: 28px; color: #6A5ACD;">Standard</h2>
      <p style="font-size: 32px; color: #6A5ACD;">$19/month</p>
      <ul style="font-size: 18px; list-style-type: none; padding: 0; margin: 20px 0;">
        <li>Up to 5 Users</li>
        <li>Standard Features</li>
        <li>Priority Email Support</li>
        <li>Up to 10 git commits/hour<li>
      </ul>
      <p style="font-size: 22px; color: #6A5ACD;">For open source projects</h3>
      <%# button style="padding: 10px 20px; background-color: #6A5ACD; color: white; border: none; border-radius: 5px; cursor: pointer;">Get Started</button %>
    </div>

    <!-- Plan 3: Premium -->
    <div style="flex: 1; min-width: 280px; border-radius: 10px; padding: 20px; text-align: center; background: linear-gradient(to bottom, rgba(30, 144, 255, 0.2), rgba(106, 90, 205, 0.2)); border: 2px solid #6A5ACD;">
      <h2 style="font-size: 28px; color: #6A5ACD;">Premium</h2>
      <p style="font-size: 32px; color: #6A5ACD;">$39/month</p>
      <ul style="font-size: 18px; list-style-type: none; padding: 0; margin: 20px 0;">
        <li>Unlimited Users</li>
        <li>All Features</li>
        <li>24/7 Support</li>
        <li>Unlimited git commits<li>
      </ul>
      <p style="font-size: 22px; color: #6A5ACD;">For the professional</h3>
      <%# button style="padding: 10px 20px; background-color: #6A5ACD; color: white; border: none; border-radius: 5px; cursor: pointer;">Get Started</button %>
    </div>
  </div>
</div>

<%= render 'footer' %>

server/app/views/welcome/testing.html.erb
<%= render 'masthead' %>

<%
  require 'lexicon'
  lexicon = Lexicon.new('app/views/welcome/testing.json')
%>
<%= javascript_include_tag('testing') %>
<%= stylesheet_link_tag('testing') %>

<h1> <%= lexicon.get('title') %> </h1>

<h3>Same React component but using different Lexicon:</h3>
<div class="JwtAuthenticatedDemo"
     data-params='{"apiUpdateUrl": "<%= APP_URL %>/update"}'
     >
  (This should be replaced by <Demo> component)
</div>

<h3>Same React component but using different Lexicon:</h3>
<div class="CorsTester"
     data-params='{"apiUpdateUrl": "<%= APP_URL %>/update"}'
     >
  (This should be replaced by <CorsTester> component)
</div>

<h3>Using Lexicon from Ruby:</h3>
<%= lexicon.get('introduction') %>

<ul>
  <li>Lexicon-Ruby version: <%= Lexicon::VERSION %></li>
  <li>Lexicon-JS version: <span class="LexiconJsVersion"/></li>
  <!--
      <li>How is Lexicon linked? <pre><%= @how_is_lexicon_module_linked %></pre></li>
  -->
</ul>